import type { BrandConfig } from "@/types/brand";
export const BRAND: BrandConfig = {
  businessName: "Gahana",
  tagline: "Your Trusted Jewellery Destination in Guruvayur",
  description: "Gahana is Guruvayur's trusted destination for gold, diamond, and silver jewellery. Serving East Nada, Guruvayur.",
  logo: "/icons/logo.svg",
  favicon: "/favicon.ico",
  heroVideo: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4",
  storyVideos: [
    { quote: "ലാളിത്യത്തിലെ പൂർണ്ണത.", description: "അണിയാൻ തീരെ ഭാരമില്ലാത്ത, എന്നാൽ കണ്ണഞ്ചിപ്പിക്കുന്ന ഡിസൈനുകൾ. നിങ്ങളുടെ ഓരോ സാധാരണ ദിവസത്തെയും മനോഹരമാക്കാൻ ഇവ മതിയാകും.", video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4", segments: { startAt: 0, loopEnd: 8 } },
    { quote: "കൈകളിൽ വിരിയുന്ന വിസ്മയം.", description: "ഓരോ ആഭരണവും ഓരോ കലാരൂപമാണ്. അതിസൂക്ഷ്മമായി, തികഞ്ഞ പൂർണ്ണതയോടെ രൂപപ്പെടുത്തിയെടുത്തവ. നിങ്ങളുടെ സ്വപ്നങ്ങൾക്ക് സ്വർണ്ണത്തിൽ ജീവൻ വയ്ക്കുമ്പോൾ.", video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4", segments: { startAt: 32, loopEnd: 40 } },
    { quote: "ഗുരുവായൂരിൻ്റെ ഹൃദയത്തിൽ നിന്ന്.", description: "ഈ നാടിൻ്റെ പൈതൃകവും പുതുമയും ഒത്തുചേരുന്ന ആഭരണങ്ങൾ. തലമുറകളായി നിങ്ങൾ നൽകുന്ന വിശ്വാസത്തിന് സ്വർണ്ണത്തേക്കാൾ തിളക്കമുണ്ട്.", video: "https://res.cloudinary.com/fylz5e3j/video/upload/v1782936959/VN20260702_013328_tbexfn.mp4", segments: { startAt: 16, loopEnd: 24 } },
  ],
  storeImages: [
    "https://res.cloudinary.com/sqsrrir4/image/upload/v1785528583/guruvayur/gahana-east-nada-store1.webp",
    "https://res.cloudinary.com/sqsrrir4/image/upload/v1785528585/guruvayur/gahana-east-nada-store2.webp",
    "https://res.cloudinary.com/sqsrrir4/image/upload/v1785528587/guruvayur/gahana-east-nada-store3.webp",
    "https://res.cloudinary.com/sqsrrir4/image/upload/v1785528590/guruvayur/gahana-east-nada-store4.webp",
  ],
  address: "East Nada, Guruvayur, Kerala 680101",
  city: "Guruvayur",
  state: "Kerala",
  pincode: "680101",
  phone: "+918089354602",
  whatsapp: "918089354602",
  email: "",
  mapsLink: "https://www.google.com/maps?cid=1006901777841213382",
  openingHours: "Mon–Sat: 9:30 AM – 8:00 PM · Sunday: 10:00 AM – 7:00 PM",
  instagram: "https://www.instagram.com/gahana_jewelgalore/",
  facebook: "https://www.facebook.com/gahana.jewel.galore/",
  seo: {
    title: "Gahana | Gold & Diamond Jewellery in Guruvayur",
    description: "Gahana — trusted jewellery store in Guruvayur. Gold, diamond, silver jewellery. East Nada, Guruvayur, Kerala.",
    keywords: [
      "Gahana",
      "jewellery Guruvayur",
      "gold jewellery Guruvayur",
      "diamond jewellery Guruvayur",
      "jewellery store East Nada",
      "jewellery Kerala",
    ],
    canonical: "https://gahana-east-nada.vercel.app",
    ogImage: "https://res.cloudinary.com/sqsrrir4/image/upload/v1785528583/guruvayur/gahana-east-nada-store1.webp",
  },
  faq: [],
  whatsappMessage: "Hello Gahana, I\'d like to know more about your jewellery collections.",
};
